# Generated by Django 2.1.4 on 2019-06-05 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Espera', 'Espera'), ('Enviada', 'Enviada')], default='Espera', max_length=20)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('imagen', models.ImageField(blank=True, default='static/img/default-img.jpg', upload_to='producto/%Y/%m/%d')),
                ('medidas', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('precio', models.IntegerField()),
                ('disponibilidad', models.BooleanField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Producto_proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('medidas', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('disponibilidad', models.BooleanField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('n_tarjeta', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
