# Generated by Django 2.1.4 on 2019-06-06 06:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buenosaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(default=datetime.datetime(2019, 6, 6, 6, 39, 25, 835204, tzinfo=utc))),
                ('hora_llegada', models.TimeField()),
                ('fecha_llegada', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_emision',
            field=models.DateField(default=datetime.datetime(2019, 6, 6, 6, 39, 25, 835204, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
