# Generated by Django 2.1.4 on 2019-06-07 03:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buenosaires', '0002_auto_20190606_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, default='Desconocida', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_emision',
            field=models.DateField(default=datetime.datetime(2019, 6, 7, 3, 43, 5, 80939, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 3, 43, 5, 80939, tzinfo=utc)),
        ),
    ]
