# Generated by Django 2.1.4 on 2019-06-07 05:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('buenosaires', '0004_auto_20190607_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_proveedor',
            name='nombre_proveedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_emision',
            field=models.DateField(default=datetime.datetime(2019, 6, 7, 5, 40, 43, 434016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 5, 40, 43, 433021, tzinfo=utc)),
        ),
    ]
