# Generated by Django 2.1.4 on 2019-06-08 03:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buenosaires', '0005_auto_20190607_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='codigo',
        ),
        migrations.AddField(
            model_name='orden',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buenosaires.Producto'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
